<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <RootNamespace>DiskCleaner.Elevated</RootNamespace>
    <AssemblyName>DiskCleaner.Elevated</AssemblyName>
    <LangVersion>12.0</LangVersion>
    <Nullable>disable</Nullable>
    <PublishTrimmed>false</PublishTrimmed>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <!-- Release 发布包剥离 pdb -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

</Project>
